name: Run Python Script

on: 
  push:
    branches:
      - main
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Clone repository
        run: |
          git clone https://github.com/hadugy42/anyonecancook
          cd anyonecancook
        
      - name: Run Python Script
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt
    
      - name: Starting Bot
        run: |
          python3 bot.py
          
        
